spring:
  profiles:
    default: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

#  datasource:
#    url: jdbc:mysql://localhost:3306/testdb?characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
#    username: scott
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:h2:mem:testdb;Mode=Oracle
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
      # 기본키 생성전략
      use-new-id-generator-mappings: false
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        #        show_sql: ture
        format_sql: true
        # 여러개 쿼리 나가야할 것을 in으로 한번에 가져옴
        default_batch_fetch_size: 100
        jdbc.batch_size: 50
        # bulk
        order_inserts: true
        order_updates: true
        dialect:
          storage_engine: innodb
    open-in-view: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 9060
#  max-http-header-size: 40KB
