create table test (
           id bigint generated by default as identity,
           created_date_time timestamp,
           modified_date_time timestamp,
           content varchar(255),
           from_email varchar(255),
           subject varchar(255),
           to_email varchar(255),
           primary key (id)
);

select * from test;